- hosts: webservers
  remote_user: ubuntu
  become: yes
  gather_facts: no
  pre_tasks:
   - name: Install Python
     raw: 'sudo apt-get -y install python'
  tasks:
   - name: Install Docker
     apt:
       name: docker.io
       state: present
   - service:
       name: docker
       state: started
       enabled: yes

