- hosts: webservers
  remote_user: ubuntu
  become: yes
  gather_facts: no
  tasks:       
   - name: Stop the container if already running
     command: bash -lc "docker stop sinatra-app || true"

   - name: Clone git repo
     git:
       repo: https://github.com/rea-cruitment/simple-sinatra-app
       dest: /home/ubuntu/simple-sinatra-app-master
     become: yes
     become_user: ubuntu

   - name: Push Dockerfile
     copy:
       src: Dockerfile
       dest: /home/ubuntu/simple-sinatra-app-master
     become: yes
     become_user: ubuntu

   - name: Build Docker
     command: bash -lc "cd /home/ubuntu/simple-sinatra-app-master && docker build -t sinatra-app ."

   - name: Run Docker
     command: bash -lc "cd /home/ubuntu/simple-sinatra-app-master && docker run -d -p 80:4567 sinatra-app"

